const int pinoLDR = A2; //PINO ANALÓGICO UTILIZADO PELO LDR
const int pinoBuzzer = 4; //PINO DIGITAL UTILIZADO PELO BUBBER

void setup(){
  pinMode(pinoLDR, INPUT); //DECLARA O PINO COMO SENDO ENTRADA
  pinMode(pinoBuzzer, OUTPUT); //DECLARA O PINO COMO SENDO SAÍDA
  Serial.begin(9600); //INICIALIZA A SERIAL
}
void loop(){
  Serial.print("LEITURA LDR: "); //ESCREVE O TEXTO NA JANELA SERIAL
  Serial.print(analogRead(pinoLDR)); //ESCREVE NA JANELA SERIAL O VALOR LIDO NO PINO ANALÓGICO

  //O VALOR "20"  PODE SER AJUSTADO, POIS O MESMO É DEFINIDO COM BASE NA LEITURA MOSTRADA NA JANELA SERIAL
  //QUANDO O SINAL DO LASER INCIDE SOB A SUPERFÍCIE DO LDR
  if (analogRead(pinoLDR) < 20){ //SE LEITURA NO PINO ANALÓGICO FOR MENOR QUE 20, FAZ
     tone(pinoBuzzer,1500,800); //ATIVA O SINAL SONORO DO BUZZER
  }else{
     noTone(pinoBuzzer); //DESATIVA O SINAL SONORO DO BUZZER
  }
}
