const int RedLED = 2; //PINO DIGITAL UTILIZADO PELO LED VERMELHO
const int GreenLED = 3; //PINO DIGITAL UTILIZADO PELO LED VERDE

void setup() {
pinMode(RedLED, OUTPUT); //DEFINE A PORTA COMO SAÍDA
pinMode(GreenLED, OUTPUT); //DEFINE A PORTA COMO SAÍDA
}
void loop(){
  digitalWrite(RedLED, HIGH); //PORTA LIGADA - A VIA 1 DO DIP SWITCH DEVE ESTAR NA POSIÇÃO ON PARA QUE O LED VERMELHO ACENDA
  digitalWrite(GreenLED, HIGH); //PORTA LIGADA -  - A VIA 2 DO DIP SWITCH DEVE ESTAR NA POSIÇÃO ON PARA QUE O LED VERDE ACENDA
}
