void setup(){
pinMode(13, OUTPUT); //DECLARA O PINO 13 COMO SENDO SAÍDA
pinMode(12, OUTPUT); //DECLARA O PINO 12 COMO SENDO SAÍDA
pinMode(11, OUTPUT); //DECLARA O PINO 11 COMO SENDO SAÍDA
}
void loop() {

digitalWrite(13, HIGH); //ENERGIZA A PORTA DIGITAL 13 E O LED ACENDE
digitalWrite(12, LOW); //DESENERGIZA A PORTA DIGITAL 12 E O LED APAGA
digitalWrite(11, LOW); //DESENERGIZA A PORTA DIGITAL 11 E O LED APAGA
delay(1000); //INTERVALO DE 1 SEGUNDO
digitalWrite(12, HIGH); //ENERGIZA A PORTA DIGITAL 12 E O LED ACENDE
digitalWrite(11, LOW); //DESENERGIZA A PORTA DIGITAL 11 E O LED APAGA
digitalWrite(13, LOW); //DESENERGIZA A PORTA DIGITAL 13 E O LED APAGA
delay(1000); //INTERVALO DE 1 SEGUNDO
digitalWrite(12, LOW); //DESENERGIZA A PORTA DIGITAL 12 E O LED APAGA
digitalWrite(13, LOW); //DESENERGIZA A PORTA DIGITAL 13 E O LED APAGA
digitalWrite(11, HIGH); //ENERGIZA A PORTA DIGITAL 11 E O LED ACENDE
delay(1000); //INTERVALO DE 1 SEGUNDO
}
