void setup() {
pinMode(13, OUTPUT); //DECLARA O PINO 13 COMO SENDO SAÍDA
}
void loop() {

digitalWrite(13, HIGH); //ENERGIZA O PINO 13 E O LED DA PLACA ACENDE
delay(1000); //INTERVALO DE 1 SEGUNDO (1000 MILISEGUNDOS = 1 SEGUNDO)

digitalWrite(13, LOW); //DESENERGIZA O PINO 13 E O LED DA PLACA APAGA
delay(1000); //INTERVALO DE 1 SEGUNDO
}
