const int portaAnalog = A2; // PORTA ANALÓGICA(A2) UTILIZADA PELO SENSOR DE TENSÃO

float valor; // DECLARAÇÃO DE VARIÁVEL QUE RECEBE O VALOR LIDO NA PORTA ANALÓGICA A2
int valFinal = 0; // DECLARAÇÃO DE VARIÁVEL QUE RECEBE O VALOR FINAL CONVERTIDO EM VOLTS AC

void setup(){
  Serial.begin(9600); // INICIALIZA A PORTA SERIAL
  pinMode(portaAnalog, INPUT); // DECLARA QUE A PORTA ANALÓGICA É UMA ENTRADA
}
void loop() {

  valFinal = 0; //REINICIA O VALOR ATUAL E ATUALIZA NA PRÓXIMA LEITURA
  valor = 0; //REINICIA O VALOR ATUAL E ATUALIZA NA PRÓXIMA LEITURA
  
  valor = analogRead(portaAnalog); //LEITURA DO VALOR NA PORTA ANALÓGICA(VARIA DE 0 ATÉ 1023)

  //BLOCO REFERENTE A TENSÃO DE 127V
  if ((valor > 100) & (valor < 483)) { //SE VARIÁVEL FOR MAIOR QUE 100 E MENOR QUE 483 FAZ
     valFinal = ((valor*5)/1023)*77.3; //VARIÁVEL RECEBE O VALOR GERADO PELA CONTA(O VALOR 77.3 PODE/DEVE SER ALTERADO PARA FINS DE AJUSTE DO VALOR DE TENSÃO)
  }
  //BLOCO REFERENTE A TENSÃO DE 220V
  if ((valor > 665) & (valor < 1023)) { //SE VARIÁVEL FOR MAIOR QUE 665 E MENOR QUE 1023 FAZ
     valFinal = ((valor*5)/1023)*57; //VARIÁVEL RECEBE O VALOR GERADO PELA CONTA(O VALOR 57 PODE/DEVE SER ALTERADO PARA FINS DE AJUSTE DO VALOR DE TENSÃO)
  }
  Serial.print("LEITURA DE: "); //SAÍDA NA JANELA COM INFORMAÇÕES DA PORTA SERIAL
  Serial.print(valFinal); //SAÍDA NA JANELA COM INFORMAÇÕES DA PORTA SERIAL
  Serial.println(" VOLTS"); //SAÍDA NA JANELA COM INFORMAÇÕES DA PORTA SERIAL
}
