#include <Thermistor.h> //INCLUSÃO DA BIBLIOTECA

Thermistor temp(2); //VARIÁVEL DO TIPO THERMISTOR, INDICANDO O PINO ANALÓGICO (A2) EM QUE O TERMISTOR ESTÁ CONECTADO
void setup() {
  Serial.begin(9600); //INICIALIZA A SERIAL
}
void loop() {
  int temperature = temp.getTemp(); //VARIÁVEL DO TIPO INTEIRO QUE RECEBE O VALOR DE TEMPERATURA CALCULADO PELA BIBLIOTECA
  Serial.print("TEMPERATURA MEDIDA: "); //ESCREVE O TEXTO NA SERIAL
  Serial.print(temperature); //ESCREVE NA JANELA SERIAL O VALOR DA TEMPERATURA
  Serial.println(" graus Celsius"); //ESCREVE O TEXTO NA SERIAL
  delay(1000); //INTERVALO DE 1 SEGUNDO
}
